apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: onlinebookstore-men
    tier: backend
    deployedBy: deploy-node-app
  name: onlinebookstore-men
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: onlinebookstore-men
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: onlinebookstore-men
        tier: backend
        deployedBy: deploy-node-app
    spec:
      containers:
        - image: 'bdfd/onlinebookstore-men:3cf9648'
          imagePullPolicy: Always
          name: onlinebookstore-men
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 150m
              memory: 128Mi
            requests:
              cpu: 3m
              memory: 64Mi
          command:
            - node
            - bin\www
          envFrom: []
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: onlinebookstore-men-regcred

